"""Add indexes to frequently queried columns

Revision ID: 47e9829871aa
Revises: e511ea623fff
Create Date: 2024-07-17 23:04:02.541113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e9829871aa'
down_revision = 'e511ea623fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ans_que_id'), ['que_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ans_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('consultant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultant_consulting_field'), ['consulting_field'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultant_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_consultant_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultant_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultant_phone'), ['phone'], unique=True)

    with op.batch_alter_table('contousers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contousers_consultant_id'), ['consultant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contousers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_price'), ['price'], unique=False)

    with op.batch_alter_table('que', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_que_que_string'), ['que_string'], unique=True)
        batch_op.create_index(batch_op.f('ix_que_que_type'), ['que_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_que_startup_stage'), ['startup_stage'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_current_startup_stage'), ['current_startup_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_ans_given'), ['is_ans_given'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    with op.batch_alter_table('userans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userans_que_id'), ['que_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userans_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('userque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userque_que_string'), ['que_string'], unique=True)
        batch_op.create_index(batch_op.f('ix_userque_que_type'), ['que_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userque_que_type'))
        batch_op.drop_index(batch_op.f('ix_userque_que_string'))

    with op.batch_alter_table('userans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userans_user_id'))
        batch_op.drop_index(batch_op.f('ix_userans_que_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_is_ans_given'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_current_startup_stage'))

    with op.batch_alter_table('que', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_que_startup_stage'))
        batch_op.drop_index(batch_op.f('ix_que_que_type'))
        batch_op.drop_index(batch_op.f('ix_que_que_string'))

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_price'))
        batch_op.drop_index(batch_op.f('ix_plan_name'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_date'))

    with op.batch_alter_table('contousers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contousers_user_id'))
        batch_op.drop_index(batch_op.f('ix_contousers_consultant_id'))

    with op.batch_alter_table('consultant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultant_phone'))
        batch_op.drop_index(batch_op.f('ix_consultant_last_name'))
        batch_op.drop_index(batch_op.f('ix_consultant_first_name'))
        batch_op.drop_index(batch_op.f('ix_consultant_email'))
        batch_op.drop_index(batch_op.f('ix_consultant_consulting_field'))

    with op.batch_alter_table('ans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ans_user_id'))
        batch_op.drop_index(batch_op.f('ix_ans_que_id'))

    # ### end Alembic commands ###
